### ISSUE TITLE
Page Controll wrong x position

### ISSUE THREAD

**Issue by Sonberg** [JellyDevelopment/JDSlider#7]
Using 2 images the page controll indicators was palced on the right side of the screen. I fixed it by changing orgin.x from self.center.x to 0

self.pageControl.frame.origin.x = 0

**Comment by TunaYangSkey** [comment]
I have the same issue

The problem arises when the UIImageView.contentMode is set to .scaleAspectFill instead of .scaleAspectFit.

**Comment by TunaYangSkey** [comment]
The pull request by gslopez perfectly resolved this problem.

**Comment by davidlcarrascal** [comment]
Thanks! Included!
